[Settings]
gtk-cursor-theme-name = wei
gtk-cursor-theme-size = 24

gtk-icon-theme-name=classic95
gtk-theme-name=Chicago95
gtk-font-name=W95FA 13

#gtk-font-antialiasing=0
#gtk-font-hinting=0
#gtk-font-hinting-slight=0
