#/etc/systemd/system/getty@tty1.service.d/autologin.conf

[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --noreset --noclear --autologin julio --keep-baud 115200,57600,38400,9600 - ${TERM}
Type=simple
