#/etc/X11/xorg.conf.d/mouse.conf

Section "InputClass"
	Identifier "Mouse Config"
	MatchIsPointer "yes"
	Driver "libinput"
	
	# Setting AccelSpeed: Valid values are between -1.0 and 1.0. 
	# 0 is the default. Positive is faster, negative is slower.
	Option "AccelSpeed" "1"

	# Setting AccelProfile: "flat" disables acceleration (raw input)
	# "adaptive" is the default (speeds up as you move faster)
	Option "AccelProfile" "flat"
EndSection
